modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "WTFPL"

[[mods]]
modId = "scriptor"
version = "${version}"
displayName = "Scriptor"
authors = "SSBlur"
description = '''
Knowledge is power!
'''
#logoFile = ""

[[dependencies.scriptor]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.scriptor]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.scriptor]]
modId = "architectury"
mandatory = true
versionRange = "[4.11.89,)"
ordering = "AFTER"
side = "BOTH"